### PR TITLE
Add some white list UT back

### PR DESCRIPTION
**Pull request by wendyliu235**

### CODE REVIEW

**Review by Zantares — APPROVED** [review]

**Comment by Zantares** [comment]
The pre-CI is exit with error msg:
```
Error: Process completed with exit code 1.
```
Is it expected?

**Comment by wendyliu235** [comment]
@Zantares  Please don't merge it, I still check the error root cause.

**Comment by wendyliu235** [comment]
@Zantares  After shengyang update the ut patch, the blacklist can add back now. Please review and merge it.

**Comment by wendyliu235** [comment]
@Zantares  I already updated to use GPU card 0,1 only, you can merge this PR now.

**Review by Zantares — APPROVED** [review]

**Pull request merged**
